sudo: required

services:
  - docker

before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/14.04/prod.list
  - sudo apt-get update -q
  - sudo apt-get install -y powershell

jobs:
  include:
    - stage: build 2.0 image
      if: tag =~ ^2\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
      script: docker build -t zeekozhu/aspnetcore-build-yarn:tmp -f 2.0/Dockerfile ./2.0
      deploy:
        - provider: script
          script: pwsh publish.ps1 $TRAVIS_TAG zeekozhu/aspnetcore-build-yarn
          on:
           tags: true
    - stage: build 2.1 images
      if: tag =~ ^2\.1\.[0-9.]+([-a-zA-Z0-9.]+)?$
      script: docker build -t zeekozhu/aspnetcore-build-yarn:tmp -f 2.1/sdk/Dockerfile ./2.1/sdk
      deploy:
        - provider: script
          script: pwsh publish.ps1 $TRAVIS_TAG zeekozhu/aspnetcore-build-yarn
          on:
            tags: true
    - script: docker build -t zeekozhu/aspnetcore-node:tmp -f 2.1/runtime/Dockerfile ./2.1/runtime
      if: tag =~ ^2\.1\.[0-9.]+([-a-zA-Z0-9.]+)?$
      deploy:
        - provider: script
          script: pwsh publish.ps1 $TRAVIS_TAG zeekozhu/aspnetcore-node
          on:
            tags: true
    - script: docker build -t zeekozhu/aspnetcore-node-deps:tmp -f 2.1/deps/Dockerfile ./2.1/deps
      if: tag =~ ^2\.1\.[0-9.]+([-a-zA-Z0-9.]+)?$
      deploy:
        - provider: script
          script: pwsh publish.ps1 $TRAVIS_TAG zeekozhu/aspnetcore-node-deps
          on:
            tags: true
