sudo: required
language: csharp
mono: none
dist: xenial
dotnet: 2.2

env: 
  - FAKE_DETAILED_ERRORS=true

services:
  - docker

jobs:
  include:
    - stage: build 2.2 images
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-build-yarn
      script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn -f 2.2/sdk/Dockerfile -c ./2.2/sdk -s ./2.2.spec.toml
      # zeekozhu/aspnetcore-build-yarn:chromium
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn:chromium -f 2.2/sdk/chromium.Dockerfile -c ./2.2/sdk -s ./2.2.spec.toml
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-node
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node -f 2.2/runtime/Dockerfile -c ./2.2/runtime -s ./2.2.spec.toml
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-node-deps used by other alpine based images
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node-deps -f 2.2/deps/Dockerfile -c ./2.2/deps -s ./2.2.spec.toml
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
    - stage: build 2.2 alpine image
      # zeekozhu/aspnetcore-node:alpine
      script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node:alpine -f 2.2/runtime/alpine.Dockerfile -c ./2.2/runtime -s ./2.2.spec.toml
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-build-yarn:alpine
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn:alpine -f 2.2/sdk/alpine.Dockerfile -c ./2.2/sdk -s ./2.2.spec.toml
      if: tag =~ ^2\.[2-9]\.[0-9.]+([-a-zA-Z0-9.]+)?$
    # 3.0
    - stage: build 3.0 images
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-build-yarn
      script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn -f 3.0/sdk/Dockerfile -c ./3.0/sdk -s ./3.0.spec.toml
      # zeekozhu/aspnetcore-build-yarn:chromium
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn:chromium -f 3.0/sdk/chromium.Dockerfile -c ./3.0/sdk -s ./3.0.spec.toml
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-node
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node -f 3.0/runtime/Dockerfile -c ./3.0/runtime -s ./3.0.spec.toml
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-node-deps used by other alpine based images
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node-deps -f 3.0/deps/Dockerfile -c ./3.0/deps -s ./3.0.spec.toml
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
    - stage: build 3.0 alpine image
      # zeekozhu/aspnetcore-node:alpine
      script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-node:alpine -f 3.0/runtime/alpine.Dockerfile -c ./3.0/runtime -s ./3.0.spec.toml
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
      # zeekozhu/aspnetcore-build-yarn:alpine
    - script: ./fake.sh build -t CI -- -t zeekozhu/aspnetcore-build-yarn:alpine -f 3.0/sdk/alpine.Dockerfile -c ./3.0/sdk -s ./3.0.spec.toml
      if: tag =~ ^3\.0\.[0-9.]+([-a-zA-Z0-9.]+)?$
    # daily
    - stage: build daily images
      script: ./fake.sh build -t daily
      if: branch = daily
