[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp"
Dotnet = "2.2.300"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = true
Suffix = "daily"
Latest = true
SkipTest = false
Daily = true

[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn:chromium"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp-chromium"
Dotnet = "2.2.300"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = true
Suffix = "chromium-daily"
Latest = false
SkipTest = false
Daily = true

[[Images]]
Name = "zeekozhu/aspnetcore-node"
Tag = "zeekozhu/aspnetcore-node"
TestImage = "zeekozhu/aspnetcore-node:tmp"
Dotnet = "2.2.5"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = false
Suffix = "daily"
Latest = true
SkipTest = false
Daily = true

[[Images]]
Name = "zeekozhu/aspnetcore-node:alpine"
Tag = "zeekozhu/aspnetcore-node"
TestImage = "zeekozhu/aspnetcore-node:tmp-alpine"
Dotnet = "2.2.5"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = false
Suffix = "alpine-daily"
Latest = false
SkipTest = false
Daily = true

[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn:alpine"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp-alpine"
Dotnet = "2.2.300"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = true
Suffix = "alpine-daily"
Latest = false
SkipTest = false
Daily = true

[[Images]]
Name = "zeekozhu/aspnetcore-node-deps"
Tag = "zeekozhu/aspnetcore-node-deps"
TestImage = "zeekozhu/aspnetcore-node-deps:tmp"
Dotnet = "2.2.5"
Node = "v12.4.0"
Yarn = "1.16.0"
Sdk = false
Suffix = "daily"
Latest = false
SkipTest = true
Daily = true
